/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Client = IDL.Record({
  'id' : IDL.Nat,
  'clientType' : IDL.Text,
  'instagram' : IDL.Text,
  'favoriteTruffles' : IDL.Text,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'importantDates' : IDL.Text,
  'isVip' : IDL.Bool,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'favoriteFlowers' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'deliveryAddress' : IDL.Text,
  'clientId' : IDL.Nat,
  'clientName' : IDL.Text,
  'createdAt' : IDL.Int,
  'deliveryDate' : IDL.Text,
  'productName' : IDL.Text,
  'deposit' : IDL.Nat,
  'occasion' : IDL.Text,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'isPickup' : IDL.Bool,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'costPrice' : IDL.Nat,
  'basePrice' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addClient' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'addOrder' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Int,
      ],
      [IDL.Nat],
      [],
    ),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOrdersByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Client = IDL.Record({
    'id' : IDL.Nat,
    'clientType' : IDL.Text,
    'instagram' : IDL.Text,
    'favoriteTruffles' : IDL.Text,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'importantDates' : IDL.Text,
    'isVip' : IDL.Bool,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'favoriteFlowers' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'deliveryAddress' : IDL.Text,
    'clientId' : IDL.Nat,
    'clientName' : IDL.Text,
    'createdAt' : IDL.Int,
    'deliveryDate' : IDL.Text,
    'productName' : IDL.Text,
    'deposit' : IDL.Nat,
    'occasion' : IDL.Text,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'isPickup' : IDL.Bool,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'costPrice' : IDL.Nat,
    'basePrice' : IDL.Nat,
  });
  
  return IDL.Service({
    'addClient' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'addOrder' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Int,
        ],
        [IDL.Nat],
        [],
      ),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOrdersByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };