/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : bigint,
  'clientType' : string,
  'instagram' : string,
  'favoriteTruffles' : string,
  'email' : string,
  'notes' : string,
  'importantDates' : string,
  'isVip' : boolean,
  'phone' : string,
  'lastName' : string,
  'favoriteFlowers' : string,
  'firstName' : string,
}
export interface Order {
  'id' : bigint,
  'status' : string,
  'deliveryAddress' : string,
  'clientId' : bigint,
  'clientName' : string,
  'createdAt' : bigint,
  'deliveryDate' : string,
  'productName' : string,
  'deposit' : bigint,
  'occasion' : string,
  'notes' : string,
  'quantity' : bigint,
  'price' : bigint,
  'isPickup' : boolean,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'category' : string,
  'costPrice' : bigint,
  'basePrice' : bigint,
}
export interface _SERVICE {
  'addClient' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
    ],
    bigint
  >,
  'updateClient' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
    ],
    boolean
  >,
  'addOrder' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      string,
      string,
      string,
      boolean,
      bigint,
      bigint,
      string,
      string,
      bigint,
    ],
    bigint
  >,
  'updateOrder' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      string,
      bigint,
      string,
      string,
      string,
      boolean,
      bigint,
      bigint,
      string,
      string,
    ],
    boolean
  >,
  'addProduct' : ActorMethod<[string, string, bigint, bigint], bigint>,
  'updateProduct' : ActorMethod<[bigint, string, string, bigint, bigint], boolean>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getOrdersByStatus' : ActorMethod<[string], Array<Order>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];